In [4]:
import pickle

In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('./Algerian_forest_fires_dataset_UPDATE.csv')
df.head()

Bejaia Region Dataset 
day month year Temperature  RH  Ws Rain  FFMC DMC DC  ISI BUI FWI              Classes  
01  06    2012 29          57  18  0     65.7 3.4 7.6 1.3 3.4 0.5            not fire   
02  06    2012 29          61  13  1.3   64.4 4.1 7.6 1   3.9 0.4            not fire   
03  06    2012 26          82  22  13.1  47.1 2.5 7.1 0.3 2.7 0.1            not fire   
04  06    2012 25          89  13  2.5   28.6 1.3 6.9 0   1.7 0              not fire

In [7]:
df.columns

Index(['Bejaia Region Dataset '], dtype='object')

In [8]:
X = df.loc[:,['Temperature', 'Ws', 'FFMC','DMC','ISI']]

y = df['FWI']

KeyError: "None of [Index(['Temperature', 'Ws', 'FFMC', 'DMC', 'ISI'], dtype='object')] are in the [columns]"

In [ ]:
from sklearnex import patch_sklearn
patch_sklearn()

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((182, 5), (61, 5), (182,), (61,))

In [ ]:
# Random forest

from sklearn.ensemble import RandomForestRegressor
RF = RandomForestRegressor(random_state=0)
RF.fit(x_train, y_train)

RandomForestRegressor(random_state=0)

In [ ]:
y_pred = RF.predict(x_test)
diff = pd.DataFrame({'Actual': y_test, 'pred': y_pred})
diff.head()

Actual    pred
140     0.4   0.389
95      0.5   0.613
6       7.2   7.366
41      0.9   0.851
110     9.7  10.231

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9709252558567671

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
RF.predict([[33,14,81.1,8.1,2.6]])

array([2.873])

In [ ]:
with open('model_reg.pickle', 'wb') as f:
    pickle.dump(RF,f)

In [ ]:
with open('model_reg.pickle', 'rb') as f:
    RF_reg_model = pickle.load(f)

In [ ]:
RF_reg_model.predict([[33,14,81.1,8.1,2.6]])

array([2.873])

In [ ]:
import bz2,pickle
file = bz2.BZ2File('Regression_trial.pkl','wb')
pickle.dump(RF,file)
file.close()

In [ ]:
R_pickle = bz2.BZ2File('Regression_trial.pkl', 'rb')
model_R = pickle.load(R_pickle)

In [ ]:
model_R.predict([[33,14,81.1,8.1,2.6]])

array([2.873])